#!/bin/bash

cmd_detection() {
	[ -z "$1" ] && echo Usage: ./am COMMAND && return
	result_text=$(type "$1" 2>&1)
	# echo $result_text
	# return
	case $result_text in
		*"not found"*)
			echo "Command not found"
			;;
		*"builtin"*)
			echo "Command is builtin"
			;;
		*"an alias for"*)
			echo "Command is an alias"
			;;
		*"shell function"*)
			echo "Command is shell function"
			;;
		*"/"*)
			echo "Command is a command"
			;;
		*)
			echo "What is that command"
			;;
	esac
}
cmd_detection "$@"
# create/read/update/delete
# add/ls/edit/rm
# create(){
# if exists ...
# echo ... >> .zshrc
# }

# read(){
# if exists
# echo it
# else doesen't exist
# }

# update(){
# if exists
# sed ...
# else echo doesn't exist
# }

# delete(){
# if alias grep alias
# else if func grep func
# else doesn't exist
# rm alias or func
# }
